accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

color0 = "#333333"
color1 = "#D35F5F"
color2 = "#FFC107"
color3 = "#b91c1c"
color4 = "#e68e0d"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
bg_light = "#1e1e1e"
bg_lighter = "#333333"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"

# Decoration (rounding, blur, opacity)
rounding = "3"
blur_size = "14"
blur_passes = "3"
opacity_active = "1.0"
opacity_inactive = "0.95"
term_opacity_active = "1.0"
term_opacity_inactive = "0.95"
popup_opacity = "0.85"

# Layout (gaps, borders)
gaps_in = "2"
gaps_out = "4"
border_size = "2"
