accent = "#82FB9C"
cursor = "#ddf7ff"
foreground = "#ddf7ff"
background = "#0B0C16"
selection_foreground = "#0B0C16"
selection_background = "#ddf7ff"

color0 = "#0B0C16"
color1 = "#50f872"
color2 = "#4fe88f"
color3 = "#50f7d4"
color4 = "#829dd4"
color5 = "#86a7df"
color6 = "#7cf8f7"
color7 = "#85E1FB"
color8 = "#6a6e95"
bg_light = "#181a2a"
bg_lighter = "#252840"
color9 = "#85ff9d"
color10 = "#9cf7c2"
color11 = "#a4ffec"
color12 = "#c4d2ed"
color13 = "#cddbf4"
color14 = "#d1fffe"
color15 = "#ddf7ff"

# Decoration (rounding, blur, opacity)
rounding = "3"
blur_size = "14"
blur_passes = "3"
opacity_active = "1.0"
opacity_inactive = "0.95"
term_opacity_active = "1.0"
term_opacity_inactive = "0.95"
popup_opacity = "0.85"

# Layout (gaps, borders)
gaps_in = "2"
gaps_out = "4"
border_size = "2"
