accent = "#7d82d9"
cursor = "#ffcead"
foreground = "#ffcead"
background = "#060B1E"
selection_foreground = "#060B1E"
selection_background = "#ffcead"

color0 = "#060B1E"
color1 = "#ED5B5A"
color2 = "#92a593"
color3 = "#E9BB4F"
color4 = "#7d82d9"
color5 = "#c89dc1"
color6 = "#a3bfd1"
color7 = "#F99957"
color8 = "#6d7db6"
bg_light = "#141932"
bg_lighter = "#1e244a"
color9 = "#faaaa9"
color10 = "#c4cfc4"
color11 = "#f7dc9c"
color12 = "#c2c4f0"
color13 = "#ead7e7"
color14 = "#dfeaf0"
color15 = "#ffcead"

# Decoration (rounding, blur, opacity)
rounding = "3"
blur_size = "14"
blur_passes = "3"
opacity_active = "0.88"
opacity_inactive = "0.80"
term_opacity_active = "0.90"
term_opacity_inactive = "0.85"
popup_opacity = "0.60"
