accent = "#7fbbb3"
cursor = "#d3c6aa"
foreground = "#d3c6aa"
background = "#2d353b"
selection_foreground = "#2d353b"
selection_background = "#d3c6aa"

color0 = "#475258"
color1 = "#e67e80"
color2 = "#a7c080"
color3 = "#dbbc7f"
color4 = "#7fbbb3"
color5 = "#d699b6"
color6 = "#83c092"
color7 = "#d3c6aa"
color8 = "#475258"
bg_light = "#374145"
bg_lighter = "#475258"
color9 = "#e67e80"
color10 = "#a7c080"
color11 = "#dbbc7f"
color12 = "#7fbbb3"
color13 = "#d699b6"
color14 = "#83c092"
color15 = "#d3c6aa"

# Decoration (rounding, blur, opacity)
rounding = "3"
blur_size = "14"
blur_passes = "3"
opacity_active = "1.0"
opacity_inactive = "0.95"
term_opacity_active = "1.0"
term_opacity_inactive = "0.95"
popup_opacity = "0.85"

# Layout (gaps, borders)
gaps_in = "2"
gaps_out = "4"
border_size = "2"
