accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

color0 = "#72696a"
color1 = "#fd6883"
color2 = "#adda78"
color3 = "#f9cc6c"
color4 = "#f38d70"
color5 = "#a8a9eb"
color6 = "#85dacc"
color7 = "#e6d9db"
color8 = "#948a8b"
bg_light = "#3d3535"
bg_lighter = "#4e4444"
color9 = "#ff8297"
color10 = "#c8e292"
color11 = "#fcd675"
color12 = "#f8a788"
color13 = "#bebffd"
color14 = "#9bf1e1"
color15 = "#f1e5e7"

# Decoration (rounding, blur, opacity)
rounding = "3"
blur_size = "14"
blur_passes = "3"
opacity_active = "1.0"
opacity_inactive = "0.95"
term_opacity_active = "1.0"
term_opacity_inactive = "0.95"
popup_opacity = "0.85"

# Layout (gaps, borders)
gaps_in = "2"
gaps_out = "4"
border_size = "2"
