accent = "#89b4fa"
cursor = "#f5e0dc"
foreground = "#b4d0fb"
background = "#1e1e2e"
selection_foreground = "#1e1e2e"
selection_background = "#f5e0dc"

color0 = "#45475a"
color1 = "#f38ba8"
color2 = "#a6e3a1"
color3 = "#f9e2af"
color4 = "#89b4fa"
color5 = "#f5c2e7"
color6 = "#94e2d5"
color7 = "#cdd6f4"
color8 = "#585b70"
bg_light = "#45475a"
bg_lighter = "#585b70"
autosuggestion = "#9399b2"
color9 = "#f38ba8"
color10 = "#a6e3a1"
color11 = "#f9e2af"
color12 = "#89b4fa"
color13 = "#f5c2e7"
color14 = "#94e2d5"
color15 = "#cdd6f4"

# Decoration (rounding, blur, opacity)
rounding = "8"
blur_size = "14"
blur_passes = "3"
opacity_active = "0.55"
opacity_inactive = "0.50"
term_opacity_active = "0.85"
term_opacity_inactive = "0.80"
popup_opacity = "0.50"

# Layout (gaps, borders)
gaps_in = "6"
gaps_out = "10"
border_size = "4"
border_active = "rgb(89b4fa) rgb(a6e3a1) 45deg"
border_inactive = "rgba(585b70aa)"
