[package]
name = "notif-center"
version = "0.10.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
serde_json = "1"
slint = { version = "1.8", default-features = false, features = ["backend-winit", "renderer-femtovg", "compat-1-2"] }
i-slint-backend-winit = "1.8"

[build-dependencies]
slint-build = "1.8"
